# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT07IssuepackstoDAG():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t07IssuepackstoDAG(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.execute_script("sessionStorage.setItem(\'github_js_actions\',\'1\')")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Pack Management Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Pack Management Test").click()
    time.sleep(2)
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=configure\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    time.sleep(2)
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.execute_script("$(\'input[name=\"cat_id\"]\').val(\'packs7\')")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    time.sleep(2)
    self.driver.execute_script("$(\'#south\').remove()")
    dropdown = self.driver.find_element(By.NAME, "enabled")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='0']").click()
    dropdown = self.driver.find_element(By.NAME, "trigger")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='F']").click()
    dropdown = self.driver.find_element(By.NAME, "form")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='visit_lab_data']").click()
    dropdown = self.driver.find_element(By.NAME, "dags")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='1']").click()
    dropdown = self.driver.find_element(By.NAME, "dags_rcpt")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='1']").click()
    dropdown = self.driver.find_element(By.NAME, "blocks")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='0']").click()
    dropdown = self.driver.find_element(By.NAME, "expire")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='0']").click()
    dropdown = self.driver.find_element(By.NAME, "packfield")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='pack_id']").click()
    dropdown = self.driver.find_element(By.NAME, "datefield")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='pack_date']").click()
    dropdown = self.driver.find_element(By.NAME, "countfield")
    dropdown.find_element(By.CSS_SELECTOR, "*[value='pack_count']").click()
    self.driver.find_element(By.NAME, "roles_view").send_keys("PackView")
    self.driver.find_element(By.NAME, "roles_dags").send_keys("PackIssue")
    self.driver.find_element(By.NAME, "roles_invalid").send_keys("PackInvalid")
    self.driver.find_element(By.NAME, "roles_assign").send_keys("PackAssign")
    self.driver.find_element(By.NAME, "roles_add").send_keys("PackAdd")
    self.driver.find_element(By.NAME, "roles_edit").send_keys("PackEdit")
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"page=configure_edit\"][href*=\"cat_id=packs7\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=packs_add\"][href*=\"cat_id=packs7\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href=\"#multiplepacks\"]").click()
    self.driver.execute_script("fd=new FormData($(\'form[enctype=\"multipart/form-data\"]\')[0]);fd.set(\'packs_upload\',new Blob([\'id\\n1\\n2\\n3\\n4\']));fetch( window.location.href, {body:fd, method:\'post\'})")
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]:not([href*=\"logout=1\"])").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=packs_list\"][href*=\"cat_id=packs7\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packrcpt")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packissue")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]").click()
    self.driver.find_element(By.ID, "new_username_assign").send_keys("user")
    self.driver.find_element(By.ID, "assignUserBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "notify_email_role")))
    self.driver.execute_script("$(\'#notify_email_role\').prop(\'checked\',false)")
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'PackIssue']").click()
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user\')]")))
    self.driver.find_element(By.ID, "new_username_assign").send_keys("user2")
    self.driver.find_element(By.ID, "assignUserBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "notify_email_role")))
    self.driver.execute_script("$(\'#notify_email_role\').prop(\'checked\',false)")
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'PackView']").click()
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user2\')]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"action=myprojects\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"logout=1\"]").click()
    self.driver.find_element(By.ID, "username").send_keys("user")
    self.driver.find_element(By.ID, "password").send_keys("abc123")
    self.driver.find_element(By.ID, "login_btn").click()
    self.driver.find_element(By.LINK_TEXT, "Pack Management Test").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"page=packs_list\"][href*=\"cat_id=packs7\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=packs_list\"][href*=\"cat_id=packs7\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packrcpt")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packissue")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"action=myprojects\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"logout=1\"]").click()
    self.driver.find_element(By.ID, "username").send_keys("user2")
    self.driver.find_element(By.ID, "password").send_keys("abc123")
    self.driver.find_element(By.ID, "login_btn").click()
    self.driver.find_element(By.LINK_TEXT, "Pack Management Test").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"prefix=pack_management\"][href*=\"page=packs\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\"page=packs_list\"][href*=\"cat_id=packs7\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"page=packs_list\"][href*=\"cat_id=packs7\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packrcpt")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".packmgmt-packissue")
    assert len(elements) == 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"action=myprojects\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"logout=1\"]").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("abc123")
    self.driver.find_element(By.ID, "login_btn").click()
    self.driver.find_element(By.LINK_TEXT, "Pack Management Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user2\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tooltipBtnRemoveProject button").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Remove user\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user2\')]")))
    self.driver.find_element(By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tooltipBtnRemoveProject button").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Remove user\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.XPATH, "//*[@id=\'user_rights_roles_table\']//td//a[contains(.,\'user\')]")))
  
